#!/bin/bash

# check all the asyCrypt scripts

# SMT timeout in seconds -- try increasing

timeout=2

check() {
  echo checking $1;
  if easycrypt -timeout $timeout $1;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

check FSetAux.ec
check ListAux.ec
check RedundantHashing.eca
check EagerEx.ec

# success!

exit 0
